# Generated by Django 4.1.2 on 2022-10-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300, verbose_name='Название')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Заставка')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('date_public', models.DateTimeField(null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog Data Base',
            },
        ),
        migrations.CreateModel(
            name='BlogHeshtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=150, null='Без темы', verbose_name='Хештег')),
                ('blog', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.blog')),
            ],
        ),
    ]
