# Generated by Django 4.1.2 on 2022-11-20 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0003_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment_user',
        ),
        migrations.RenameField(
            model_name='comment_user',
            old_name='coment',
            new_name='comment',
        ),
    ]
