# Generated by Django 4.1.2 on 2022-12-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0005_alter_comment_user_post_alter_comment_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_user',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navigation.blog'),
        ),
        migrations.AlterField(
            model_name='comment_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
