# Generated by Django 4.1.2 on 2022-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_alter_comment_user_post_alter_comment_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='data_time',
            field=models.DateTimeField(null=True),
        ),
    ]
