# Generated by Django 4.1.2 on 2022-12-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_comment_user_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_user',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='navigation.blog'),
        ),
    ]
