# Generated by Django 4.1.2 on 2022-12-11 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0009_alter_comment_user_data_time_alter_comment_user_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_user',
            name='data_time',
        ),
        migrations.AddField(
            model_name='comment_user',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_user',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment_user',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='navigation.blog'),
        ),
        migrations.AlterField(
            model_name='comment_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
