# Generated by Django 4.1.2 on 2022-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_remove_comment_user_data_time_comment_user_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='benefit',
            field=models.IntegerField(default=0),
        ),
    ]
