# Generated by Django 4.1.2 on 2022-12-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_comment_user_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_user',
            old_name='benefit',
            new_name='dislike',
        ),
        migrations.AddField(
            model_name='comment_user',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
