# Generated by Django 4.1.2 on 2023-01-01 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0012_rename_benefit_comment_user_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_user',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment_user',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_user',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
