# Generated by Django 4.1.2 on 2023-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_remove_comment_user_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(max_length=20, null=True, verbose_name='Тип статьи'),
        ),
    ]
