# Generated by Django 4.1.7 on 2023-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_blog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=150, null='Без темы', verbose_name='Хештег')),
            ],
        ),
    ]
