# Generated by Django 4.1.2 on 2022-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_journalist',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Статус журналиста'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Репутация'),
        ),
    ]
