# Generated by Django 4.1.2 on 2022-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../media/avatar/avatar_none.png', null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
