# Generated by Django 4.1.2 on 2022-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../media/avatar/avatar_none.png', upload_to='', verbose_name='Аватарка'),
        ),
    ]
