# Generated by Django 4.1.2 on 2022-12-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar_none.png', upload_to='media/avatar', verbose_name='Аватарка'),
        ),
    ]
